-- Generado por scripts/seed-roles.js (parche 16.19.1). No editar a mano.
insert into public.champion_roles (champion_id, roles) values
  ('Aatrox', array['top']::text[]),
  ('Ahri', array['mid']::text[]),
  ('Akali', array['mid', 'top']::text[]),
  ('Akshan', array['mid', 'top']::text[]),
  ('Alistar', array['utility']::text[]),
  ('Ambessa', array['top', 'jungle']::text[]),
  ('Amumu', array['jungle']::text[]),
  ('Anivia', array['mid']::text[]),
  ('Annie', array['mid', 'utility']::text[]),
  ('Aphelios', array['bottom']::text[]),
  ('Ashe', array['bottom', 'utility']::text[]),
  ('AurelionSol', array['mid']::text[]),
  ('Aurora', array['mid', 'top']::text[]),
  ('Azir', array['mid']::text[]),
  ('Bard', array['utility']::text[]),
  ('Belveth', array['jungle']::text[]),
  ('Blitzcrank', array['utility']::text[]),
  ('Brand', array['utility', 'jungle', 'mid']::text[]),
  ('Braum', array['utility']::text[]),
  ('Briar', array['jungle']::text[]),
  ('Caitlyn', array['bottom']::text[]),
  ('Camille', array['top', 'utility']::text[]),
  ('Cassiopeia', array['mid']::text[]),
  ('Chogath', array['top', 'mid']::text[]),
  ('Corki', array['mid', 'bottom']::text[]),
  ('Darius', array['top']::text[]),
  ('Diana', array['jungle', 'mid']::text[]),
  ('DrMundo', array['top', 'jungle']::text[]),
  ('Draven', array['bottom']::text[]),
  ('Ekko', array['jungle', 'mid']::text[]),
  ('Elise', array['jungle']::text[]),
  ('Evelynn', array['jungle']::text[]),
  ('Ezreal', array['bottom']::text[]),
  ('Fiddlesticks', array['jungle']::text[]),
  ('Fiora', array['top']::text[]),
  ('Fizz', array['mid']::text[]),
  ('Galio', array['mid', 'utility']::text[]),
  ('Gangplank', array['top', 'mid']::text[]),
  ('Garen', array['top']::text[]),
  ('Gnar', array['top']::text[]),
  ('Gragas', array['top', 'jungle', 'mid']::text[]),
  ('Graves', array['jungle']::text[]),
  ('Gwen', array['top', 'jungle']::text[]),
  ('Hecarim', array['jungle']::text[]),
  ('Heimerdinger', array['mid', 'top', 'utility']::text[]),
  ('Hwei', array['mid', 'utility']::text[]),
  ('Illaoi', array['top']::text[]),
  ('Irelia', array['top', 'mid']::text[]),
  ('Ivern', array['jungle', 'utility']::text[]),
  ('Janna', array['utility']::text[]),
  ('JarvanIV', array['jungle']::text[]),
  ('Jax', array['top', 'jungle']::text[]),
  ('Jayce', array['top', 'mid']::text[]),
  ('Jhin', array['bottom']::text[]),
  ('Jinx', array['bottom']::text[]),
  ('KSante', array['top']::text[]),
  ('Kaisa', array['bottom']::text[]),
  ('Kalista', array['bottom']::text[]),
  ('Karma', array['utility', 'mid', 'top']::text[]),
  ('Karthus', array['jungle', 'bottom']::text[]),
  ('Kassadin', array['mid']::text[]),
  ('Katarina', array['mid']::text[]),
  ('Kayle', array['top', 'mid']::text[]),
  ('Kayn', array['jungle']::text[]),
  ('Kennen', array['top', 'mid']::text[]),
  ('Khazix', array['jungle']::text[]),
  ('Kindred', array['jungle']::text[]),
  ('Kled', array['top']::text[]),
  ('KogMaw', array['bottom']::text[]),
  ('Leblanc', array['mid']::text[]),
  ('LeeSin', array['jungle']::text[]),
  ('Leona', array['utility']::text[]),
  ('Lillia', array['jungle', 'top']::text[]),
  ('Lissandra', array['mid']::text[]),
  ('Locke', array['mid']::text[]),
  ('Lucian', array['bottom', 'mid']::text[]),
  ('Lulu', array['utility']::text[]),
  ('Lux', array['utility', 'mid']::text[]),
  ('Malphite', array['top', 'utility']::text[]),
  ('Malzahar', array['mid']::text[]),
  ('Maokai', array['utility', 'jungle', 'top']::text[]),
  ('MasterYi', array['jungle']::text[]),
  ('Mel', array['utility', 'mid']::text[]),
  ('Milio', array['utility']::text[]),
  ('MissFortune', array['bottom']::text[]),
  ('Mordekaiser', array['top', 'jungle']::text[]),
  ('Morgana', array['utility', 'jungle']::text[]),
  ('Naafiri', array['mid', 'top']::text[]),
  ('Nami', array['utility']::text[]),
  ('Nasus', array['top']::text[]),
  ('Nautilus', array['utility']::text[]),
  ('Neeko', array['mid', 'utility']::text[]),
  ('Nidalee', array['jungle']::text[]),
  ('Nilah', array['bottom']::text[]),
  ('Nocturne', array['jungle']::text[]),
  ('Nunu', array['jungle']::text[]),
  ('Olaf', array['top', 'jungle']::text[]),
  ('Orianna', array['mid']::text[]),
  ('Ornn', array['top']::text[]),
  ('Pantheon', array['utility', 'mid', 'top', 'jungle']::text[]),
  ('Poppy', array['top', 'jungle', 'utility']::text[]),
  ('Pyke', array['utility', 'mid']::text[]),
  ('Qiyana', array['mid', 'jungle']::text[]),
  ('Quinn', array['top']::text[]),
  ('Rakan', array['utility']::text[]),
  ('Rammus', array['jungle']::text[]),
  ('RekSai', array['jungle']::text[]),
  ('Rell', array['utility', 'jungle']::text[]),
  ('Renata', array['utility']::text[]),
  ('Renekton', array['top']::text[]),
  ('Rengar', array['jungle', 'top']::text[]),
  ('Riven', array['top']::text[]),
  ('Rumble', array['top', 'mid']::text[]),
  ('Ryze', array['mid', 'top']::text[]),
  ('Samira', array['bottom']::text[]),
  ('Sejuani', array['jungle', 'top']::text[]),
  ('Senna', array['utility', 'bottom']::text[]),
  ('Seraphine', array['utility', 'mid', 'bottom']::text[]),
  ('Sett', array['top', 'mid', 'utility']::text[]),
  ('Shaco', array['jungle', 'utility']::text[]),
  ('Shen', array['top', 'utility']::text[]),
  ('Shyvana', array['jungle']::text[]),
  ('Singed', array['top']::text[]),
  ('Sion', array['top']::text[]),
  ('Sivir', array['bottom']::text[]),
  ('Skarner', array['jungle', 'top']::text[]),
  ('Smolder', array['bottom', 'mid']::text[]),
  ('Sona', array['utility']::text[]),
  ('Soraka', array['utility']::text[]),
  ('Swain', array['utility', 'mid', 'bottom']::text[]),
  ('Sylas', array['mid', 'jungle', 'top']::text[]),
  ('Syndra', array['mid']::text[]),
  ('TahmKench', array['top', 'utility']::text[]),
  ('Taliyah', array['jungle', 'mid']::text[]),
  ('Talon', array['mid', 'jungle']::text[]),
  ('Taric', array['utility']::text[]),
  ('Teemo', array['top']::text[]),
  ('Thresh', array['utility']::text[]),
  ('Tristana', array['bottom', 'mid']::text[]),
  ('Trundle', array['top', 'jungle']::text[]),
  ('Tryndamere', array['top']::text[]),
  ('TwistedFate', array['mid']::text[]),
  ('Twitch', array['bottom', 'utility']::text[]),
  ('Udyr', array['jungle', 'top']::text[]),
  ('Urgot', array['top']::text[]),
  ('Varus', array['bottom', 'mid']::text[]),
  ('Vayne', array['bottom', 'top']::text[]),
  ('Veigar', array['mid', 'utility', 'bottom']::text[]),
  ('Velkoz', array['utility', 'mid']::text[]),
  ('Vex', array['mid']::text[]),
  ('Vi', array['jungle']::text[]),
  ('Viego', array['jungle']::text[]),
  ('Viktor', array['mid']::text[]),
  ('Vladimir', array['mid', 'top']::text[]),
  ('Volibear', array['top', 'jungle']::text[]),
  ('Warwick', array['jungle', 'top']::text[]),
  ('MonkeyKing', array['top', 'jungle']::text[]),
  ('Xayah', array['bottom']::text[]),
  ('Xerath', array['utility', 'mid']::text[]),
  ('XinZhao', array['jungle']::text[]),
  ('Yasuo', array['mid', 'top', 'bottom']::text[]),
  ('Yone', array['mid', 'top']::text[]),
  ('Yorick', array['top']::text[]),
  ('Yunara', array['bottom']::text[]),
  ('Yuumi', array['utility']::text[]),
  ('Zaahen', array['top', 'jungle']::text[]),
  ('Zac', array['jungle', 'top']::text[]),
  ('Zed', array['mid', 'jungle']::text[]),
  ('Zeri', array['bottom']::text[]),
  ('Ziggs', array['mid', 'bottom']::text[]),
  ('Zilean', array['utility', 'mid']::text[]),
  ('Zoe', array['mid']::text[]),
  ('Zyra', array['utility']::text[])
on conflict (champion_id) do update set roles = excluded.roles;
